[package]
name = "simd-check"
version = "0.1.0"
edition = "2024"
authors = ["Daniel Olabemiwo"]

[dependencies]

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
name = "simd_benchmarks"
harness = false
